version: '3.8'

services:

  server:
    build: .
    image: server:0.0.1
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - webnet
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
      - server

  grafana:
    image: grafana/grafana:9.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  webnet:
    driver: bridge